name: Run UI-Automation Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: setup Selenoid Infrastructure
        run: ./selenoid_start.sh

      - name: test with chrome browser
        run: ./gradlew clean -Pthread=3 -Plaunch=remote testChrome
        continue-on-error: true

      - name: test with firefox browser
        run: ./gradlew clean -Pthread=3 -Plaunch=remote testFirefox
        continue-on-error: true

      - name: get Allure history
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      - name: generate Allure report
        if: always()
        run: ./gradlew allureReport
        continue-on-error: true

      - name: deploy Allure report
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: build/reports/allure-report
