name: Run UI-Automation Tests

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '0 2 * * 0-6'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LANG: en_US.UTF-8
      LC_CTYPE: en_US.UTF-8

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Set up Selenoid Infrastructure
        run: ./selenoid_start.sh

      - name: Run UI-Automation tests with Chrome browser
        run: ./gradlew clean -Pthread=3 -Plaunch=remote testChrome

      - name: Generate Allure report
        if: always()
        run: ./gradlew allureReport

      - name: Deploy Allure report
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: build/reports/allure-report

      - uses: actions/upload-artifact@v2
        if: always()
        with:
         name: allure report
         path: build/reports/allure-report
